# Generated by Django 5.2.8 on 2025-11-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='Campo vazio'),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Sem título', max_length=100),
        ),
    ]
