# Generated by Django 5.2.8 on 2025-11-21 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teste_api', '0003_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='owner',
        ),
    ]
